### ISSUE TITLE
rs.DataSet.assign_resolution_bins ought to return bin edges

### ISSUE THREAD

**Issue by kmdalton** [Hekstra-Lab/reciprocalspaceship#184]
The current bin labels assume formatting that takes up too much space. It would be better if this method just returned bin edges which users can treat however they want.

**Comment by JBGreisman** [comment]
yep -- agreed. This is already supported in `rs.utils.binning`, so it makes sense to extend that functionality to the `DataSet` method. I could see two possible additions/changes:

1. Change signature to: `DataSet.assign_resolution_bins(..., return_edges=False, return_labels=False)`so that you can get bin edges or formatted labels depending on your use case. 
2. Assign resolution bins currently only takes an integer specifying the number of bins to assign. If you give it a monotonic list/array/tuple, should we have it treat those as bin edges to assign the reflections to those bins?

I think (1) is a very small change, and (2) will be slightly more work but is already largely supported in `rs.utils.binning`. Let me know if you have thoughts on this.
