### ISSUE TITLE
Unstack anomalous taking into account Careless repeats

### ISSUE THREAD

**Issue by DHekstra** [Hekstra-Lab/reciprocalspaceship#193]
At https://github.com/Hekstra-Lab/reciprocalspaceship/blob/98409cc8552d22d03d6100c6c1dd01cc369e9647/reciprocalspaceship/dataset.py#L1144  

I would like to propose replacing 
```
result = dataset_plus.merge(
            dataset_minus, how="outer", on=["H", "K", "L"], suffixes=suffixes
        )
```

with something like 
```
    if "repeat" in dataset_plus.columns:
        result = dataset_plus.merge(
                dataset_minus, how="outer", on=["H", "K", "L","repeat"], suffixes=suffixes
        )
    else:
        result = dataset_plus.merge(
                dataset_minus, how="outer", on=["H", "K", "L"], suffixes=suffixes
        )

```

**Comment by DHekstra** [comment]
Ihis would be helpful for CCanom calculation on Careless _xval_#.mtz files using rsbooster.stats.ccanom.analyze_ccanom_mtz() directly. It is obviously not essential, since I could just use the make_halves_ccanom function in the same location first, but it seems undesirable for the default behavior to be to randomly pair repeats.

**Comment by kmdalton** [comment]
i have a feeling this is better handled at the top level by the user with a `ds.groupby("repeat").apply(lambda x: x.merge(...))` or some similar formula. perhaps share the code you're working on and we can recommend a strategy.

**Comment by DHekstra** [comment]
the workaround in this case is quite simple--the problem only occurs if I stack and then unstack--then the repeats no longer match up. So the workaround is not to stack in the first place.

**Comment by DHekstra** [comment]
Good point. I'm going the `groupby` route for now, going off what is implemented in `rsbooster.stats.anom.py`.

**Comment by DHekstra** [comment]
my initial take was that the `"repeat"` was a sufficiently common case (for me, anyways) that we might want to implement a provision for it.

**Comment by kmdalton** [comment]
yeah i think this use case is going to be pretty unusual outside the hekstra lab. i don't think any other program besides careless makes this sort of data structure. this is maybe an indicator that careless shouldn't make these sorts of files :thinking:

**Comment by JBGreisman** [comment]
My personal feeling is that `rs` should be kept agnostic to `careless` decisions regarding column naming. More broadly, I try to avoid any hard-coded column names, because I think that's a recipe for problematic corner cases and "user surprise." There are certainly exceptions for `H`, `K`, and `L` and some internal column names, but generally I'd like to avoid hardcoding a case for `repeat`.

As @kmdalton said, in my mind, the `xval` mtz that gets output should be considered "unmerged" because it has repeat Miller indices. To my knowledge, `CCanom` can be computed from careless output without any use of `{stack/unstack}_anomalous` -- there is a commandline tool `rs.ccanom` provided in `rsbooster` that should be applicable to careless `xval` output without any modification needed. If you're running into cases of careless output that are unsupported by it, please let me know or file a ticket on `rsbooster`. `rs.ccanom -h` can be used to see the arguments it takes. Its internals can also be used as a framework for implementing your own function if that is more useful. 

Let me know if there's anything else I can provide as far as useful snippets/templates

**Comment by DHekstra** [comment]
OK, after some consideration, I agree with all of these design decisions. I agree that the commandline application supports this case already well. Part of the issue came from me wanting to call a function in rsbooster.stats.ccanom directly from in a notebook (which works fine as long as one is aware of the above). My goal is to provide some better support for Careless users who are trying to understand how to interpret the Careless output.

**Comment by DHekstra** [comment]
For future reference, this is a productive work-around:

```
half_repeats=[]
for repeat in out.repeat.unique():
    for half in range(2):
        half_repeat=tmp.loc[(tmp.repeat==repeat) & (tmp.half==half),["F","SigF","I","SigI","N","high$
        half_repeat=half_repeat.unstack_anomalous()
        half_repeat["half"]=half
        half_repeat["half"]=half_repeat["half"].astype('MTZInt')
        half_repeat["repeat"]=repeat
        half_repeat["repeat"]=half_repeat["repeat"].astype('MTZInt')
        half_repeats.append(half_repeat)

out2=rs.concat(half_repeats)
```
