### ISSUE TITLE
rs.DataSet constructor doesn't populate _cache_index_dtypes

### ISSUE THREAD

**Issue by kmdalton** [Hekstra-Lab/reciprocalspaceship#21]
The following minimal snippet illustrates how to reproduce the issue. If a `DataSet` is constructed without an explicit `index` object, the constructor won't populate `self._cache_index_dtypes`. This has a lot of nasty side effects, and exposes users to some pretty cryptic error messages. 

```python
import reciprocalspaceship as rs
import numpy as np


inFN = 'reciprocalspaceship/tests/data/algorithms/HEWL_SSAD_24IDC.mtz'
mtz = rs.read_mtz(inFN)

mtz = rs.DataSet({
        'I' : mtz['IMEAN'],
        'SigI' : mtz['SIGIMEAN'],
    }, 
    cell = mtz.cell, 
    spacegroup=mtz.spacegroup
)
```

The issue that tipped me off to this pathology was when i tried to call `DataSet.infer_mtz_dtypes`. 

```python
Traceback (most recent call last):
  File "dtypes_bug.py", line 16, in <module>
    mtz.infer_mtz_dtypes()
  File "/home/kmdalton/opt/reciprocalspaceship/reciprocalspaceship/dataset.py", line 38, in wrapped
    return f(ds.copy(), *args, **kwargs)
  File "/home/kmdalton/opt/reciprocalspaceship/reciprocalspaceship/dataset.py", line 658, in infer_mtz_dtypes
    self.reset_index(inplace=True, level=index_keys)
  File "/home/kmdalton/opt/reciprocalspaceship/reciprocalspaceship/dataset.py", line 271, in reset_index
    _handle_cached_dtypes(self, columns, drop)
  File "/home/kmdalton/opt/reciprocalspaceship/reciprocalspaceship/dataset.py", line 265, in _handle_cached_dtypes
    dtype = dataset._cache_index_dtypes.pop(key)
KeyError: 'H'
```

**Comment by kmdalton** [comment]
Explicitly passing an index to the constructor doesn't solve the issue. I thought it would, but it doesn't:

```python
import reciprocalspaceship as rs
import numpy as np


inFN = 'reciprocalspaceship/tests/data/algorithms/HEWL_SSAD_24IDC.mtz'
mtz = rs.read_mtz(inFN)

mtz = rs.DataSet({
        'I' : mtz['IMEAN'],
        'SigI' : mtz['SIGIMEAN'],
    }, 
    cell = mtz.cell, 
    spacegroup=mtz.spacegroup,
    index=mtz.index,
)

mtz.infer_mtz_dtypes()
```

```python
Traceback (most recent call last):
  File "dtypes_bug.py", line 17, in <module>
    mtz.infer_mtz_dtypes()
  File "/home/kmdalton/opt/reciprocalspaceship/reciprocalspaceship/dataset.py", line 38, in wrapped
    return f(ds.copy(), *args, **kwargs)
  File "/home/kmdalton/opt/reciprocalspaceship/reciprocalspaceship/dataset.py", line 658, in infer_mtz_dtypes
    self.reset_index(inplace=True, level=index_keys)
  File "/home/kmdalton/opt/reciprocalspaceship/reciprocalspaceship/dataset.py", line 271, in reset_index
    _handle_cached_dtypes(self, columns, drop)
  File "/home/kmdalton/opt/reciprocalspaceship/reciprocalspaceship/dataset.py", line 265, in _handle_cached_dtypes
    dtype = dataset._cache_index_dtypes.pop(key)
KeyError: 'H'
```

**Comment by JBGreisman** [comment]
Yep -- this seems like a bug to me. This is a case where the private attribute for preserving mtz dtypes can get out of sync with the actual index. In my mind this should be fixed by initializing the attribute to something sane, such as the current dtypes of the index. In many cases, this will not be the best possible dtype -- often `object` dtypes for MultiIndexes -- but it will be the best that can be do without additional information.

**Comment by JBGreisman** [comment]
For the record, this sort of issue can also result from different methods of calling `DataSet.set_index()`:

```python
import reciprocalspaceship as rs
import numpy as np

mtz = rs.read_mtz("tests/data/fmodel/9LYZ.mtz")
print(mtz._index_dtypes_cache) # prints {'H': 'HKL', 'K': 'HKL', 'L': 'HKL'}

mtz.set_index(np.arange(168), append=True,  inplace=True)
print(mtz._index_dtypes_cache) # prints int64
```

In the above example, adding a numpy array to the index wiped out the existing cache.

**Comment by JBGreisman** [comment]
It is worth noting that I don't think there is a general way to handle initializing the `DataSet._index_dtypes` attribute in the original snippet that started this issue. This is because pandas coerces any `ExtensionDtype` in an index to an `object` dtype, so it's not possible to figure out what the original dtype was. This is the main idea for why the `DataSet._index_dtypes` attribute is used in `rs`. It is always possible to make this work as expected with a call to `__finalize__`:
```python
import reciprocalspaceship as rs
import numpy as np


inFN = 'reciprocalspaceship/tests/data/algorithms/HEWL_SSAD_24IDC.mtz'
mtz = rs.read_mtz(inFN)

mtz2 = rs.DataSet({
        'I' : mtz['IMEAN'],
        'SigI' : mtz['SIGIMEAN'],
    }, 
    cell = mtz.cell, 
    spacegroup=mtz.spacegroup
)
mtz2.__finalize__(mtz)
```
The above PR improves the robustness of `reset_index()` and `set_index()` to "fail gracefully" in cases where it hasn't cached the original dtype. In such instances, it defaults to the standard pandas behavior. This compromise avoids the cryptic error messages above.
