### ISSUE TITLE
There should be an rs.read_csv method

### ISSUE THREAD

**Issue by kmdalton** [Hekstra-Lab/reciprocalspaceship#32]
I was just trying to load a precognition strong spot file which is just a whitespace delimited text file

```
$ head precognition_integration/e080_001.mccd.re.spt
    0    0    0    2102.28  2175.12      43575.2      290.0
    0    0    0    1429.60  1791.03      19469.1      197.7
    0    0    0    2365.19  1508.56      13289.9      161.6
    0    0    0    2677.00  2137.74      13169.7      161.6
    0    0    0    1572.55  2012.03       9752.7      141.7
    0    0    0    2319.03  2529.97       7220.5      120.4
    0    0    0    1562.52  1850.75       7231.6      123.0
    0    0    0    1818.91  2197.97       6648.6      117.0
    0    0    0    1863.79  1514.90       6607.9      118.2
    0    0    0    1514.11  2559.16       6274.7      112.7
```

`rs.read_precognition` fails for this sort of file which is arguably a bug or a design choice. I'm personally not very concerned about that distinction. What concerns me is that this is a very reasonable file format for reflections and I have no good way to get it into a `DataSet`. Best I can figure is to pass it through pandas as follows

```python
import pandas as pd
import reciprocalspaceship as rs

inFN = "precognition_integration/e080_001.mccd.re.spt"


df = pd.read_csv(inFN, delim_whitespace=True, names=["H", "K", "L", "X", "Y", "I", "SIGI"])
ds = rs.DataSet(df).infer_mtz_dtypes()
```
Now, this is not super onerous or anything, but I usually don't keep pandas in my imports when working with `rs`. So it is two extra steps that would just go away if we could do:

```python
ds = rs.read_csv(
  inFN, 
  delim_whitespace=True, 
  names=["H", "K", "L", "X", "Y", "I", "SIGI"], 
  infer_dtypes=True
)
```

Am I just being cranky or is this a good addition? Does this break any of our API decisions?

**Comment by JBGreisman** [comment]
Currently, `rs.read_precognition()` is written to only support `.ii` integrated intensity files and `.hkl` scaled/merged HKL files.

I agree that it makes sense to support CSV files without needing to go through a `pandas.DataFrame` because it is such a general / widely-used file format. This support can easily be added by wrapping a call to `pd.read_csv()` and adding an additional `infer_dtypes` boolean flag or something like that as you included. 

For this specific case, it may be worth adding `.spt` files to the supported file formats in `rs.read_precognition()`.  At the very least, I should update the docstring to specify the supported files.
